api_platform:
    swagger:
        versions: [3]
        api_keys:
            myAuth:
                name: Authorization
                type: header
    title: 'Recipes API'
    description: 'Great delicious recipes !'
    version: 1.0.0
    show_webby: false
    openapi:
        contact:
            name: L4houx
            url: https://github.com/l4houx
            #email: 
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
