twig:
    file_name_pattern: '*.twig'
    #form_themes: ['bootstrap_5_layout.html.twig']
    form_themes: ['form/layout.html.twig']

    globals:
        # Setting
        setting: '@App\Service\SettingService'

        # Language
        locales: "%app_locales%"

        # Google
        google_maps_api_key: "%google_maps_api_key%"

        # Date and time
        date_format: "%date_format%"
        date_format_date_only: "%date_format_date_only%"
        date_timezone: "%date_timezone%"

        website_name: '%env(WEBSITE_NAME)%'
        website_url: '%env(WEBSITE_URL)%'

        name: '%env(WEBSITE_CONTACT_NAME)%'
        email: '%env(WEBSITE_CONTACT_EMAIL)%'
        address: '%env(WEBSITE_CONTACT_ADDRESS)%'
        company: '%env(WEBSITE_COMPANY)%'
        law: '%env(WEBSITE_LAW)%'
        phone: '%env(WEBSITE_CONTACT_PHONE)%'
        siret: '%env(WEBSITE_SIRET)%'
        ape: '%env(WEBSITE_APE)%'
        vat: '%env(WEBSITE_VAT)%'
        quantity: '%env(WEBSITE_QUANTITY)%'
        host: '%env(WEBSITE_HOST)%'
        domain: '%env(WEBSITE_DOMAIN)%'
        facebook_url: '%env(WEBSITE_FACEBOOK_URL)%'
        instagram_url: '%env(WEBSITE_INSTAGRAM_URL)%'
        youtube_url: '%env(WEBSITE_YOUTUBE_URL)%'
        twitter_url: '%env(WEBSITE_TWITTER_URL)%'
        github_url: '%env(WEBSITE_GITHUB_URL)%'

    date:
        format: "%date_format%"
        timezone: "%date_timezone%"

when@test:
    twig:
        strict_variables: true
