vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:

        recipe_image:
            uri_prefix: '%recipe_image%'
            upload_destination: '%kernel.project_dir%/public%recipe_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            #inject_on_load: true
            #delete_on_update: true
            #delete_on_remove: true

        post_image:
            uri_prefix: '%post_image%'
            upload_destination: '%kernel.project_dir%/public%post_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            #inject_on_load: true
            #delete_on_update: true
            #delete_on_remove: true

        homepage_hero_custom_background:
            uri_prefix: '%homepage_hero_custom_background%'
            upload_destination: '%kernel.project_dir%/public%homepage_hero_custom_background%'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        app_layout:
            uri_prefix: '%app_layout%'
            upload_destination: '%kernel.project_dir%/public%app_layout%'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        icon:
            upload_destination: '%kernel.project_dir%/public%icon%'
            uri_prefix: '%icon%'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug' }

        attachments:
            uri_prefix: '%attachments%'
            upload_destination: '%kernel.project_dir%/public%attachments%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y' # will create directory "2023/13/01" for curent date "2023-01-13"
                    date_time_property: createdAt # see above example
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
