vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:

        restaurant_logo:
            uri_prefix: /uploads/restaurants
            upload_destination: '%kernel.project_dir%/public/uploads/restaurants'
            namer: vich_uploader.namer_uniqid

        restaurant_cover:
            uri_prefix: /uploads/restaurants/covers
            upload_destination: '%kernel.project_dir%/public/uploads/restaurants/covers'
            namer: vich_uploader.namer_uniqid

        category_image:
            uri_prefix: /uploads/categories
            upload_destination: '%kernel.project_dir%/public/uploads/categories'
            namer: vich_uploader.namer_uniqid

        recipe_image:
            uri_prefix: /uploads/recipes
            upload_destination: '%kernel.project_dir%/public/uploads/recipes'
            namer: vich_uploader.namer_uniqid

        post_image:
            uri_prefix: /uploads/post
            upload_destination: '%kernel.project_dir%/public/uploads/post'
            namer: vich_uploader.namer_uniqid

        homepage_hero_custom_background:
            uri_prefix: /uploads/home
            upload_destination: '%kernel.project_dir%/public/uploads/home'
            namer: vich_uploader.namer_uniqid

        homepage_hero_custom_block_one:
            uri_prefix: /uploads/home/block
            upload_destination: '%kernel.project_dir%/public/uploads/home/block'
            namer: vich_uploader.namer_uniqid

        homepage_hero_custom_block_two:
            uri_prefix: /uploads/home/block
            upload_destination: '%kernel.project_dir%/public/uploads/home/block'
            namer: vich_uploader.namer_uniqid

        homepage_hero_custom_block_three:
            uri_prefix: /uploads/home/block
            upload_destination: '%kernel.project_dir%/public/uploads/home/block'
            namer: vich_uploader.namer_uniqid

        app_layout:
            uri_prefix: /uploads/layout
            upload_destination: '%kernel.project_dir%/public/uploads/layout'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        icon:
            uri_prefix: /uploads/icon
            upload_destination: '%kernel.project_dir%/public/uploads/icon'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug' }

        attachments:
            uri_prefix: uploads/attachments
            upload_destination: '%kernel.project_dir%/public/uploads/attachments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y' # will create directory "2023/13/01" for curent date "2023-01-13"
                    date_time_property: createdAt # see above example
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        audience_image:
            uri_prefix: /uploads/audiences
            upload_destination: '%kernel.project_dir%/public/uploads/audiences'
            namer: vich_uploader.namer_uniqid

        venue_image:
            uri_prefix: /uploads/venues
            upload_destination: '%kernel.project_dir%/public/uploads/venues'
            namer: vich_uploader.namer_uniqid

        user_avatar:
            uri_prefix: /uploads/user
            upload_destination: '%kernel.project_dir%/public/uploads/user'
            namer: vich_uploader.namer_uniqid

        user_team:
            uri_prefix: /uploads/user/team
            upload_destination: '%kernel.project_dir%/public/uploads/user/team'
            namer: vich_uploader.namer_uniqid