<?php

namespace App\DataFixtures;

use App\Entity\Setting\Language;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Bundle\FixturesBundle\FixtureGroupInterface;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\String\Slugger\SluggerInterface;

class AppLanguageFixtures extends Fixture implements FixtureGroupInterface
{
    public function __construct(
        private readonly SluggerInterface $slugger
    ) {
    }

    public static function getGroups(): array
    {
        return ['languages'];
    }

    public function load(ObjectManager $manager): void
    {
        $languages_en = [
            'en' => 'English',
            'aa' => 'Afar',
            'ab' => 'Abkhazian',
            'af' => 'Afrikaans',
            'am' => 'Amharic',
            'ar' => 'Arabic',
            'as' => 'Assamese',
            'ay' => 'Aymara',
            'az' => 'Azerbaijani',
            'ba' => 'Bashkir',
            'be' => 'Byelorussian',
            'bg' => 'Bulgarian',
            'bh' => 'Bihari',
            'bi' => 'Bislama',
            'bn' => 'Bengali/Bangla',
            'bo' => 'Tibetan',
            'br' => 'Breton',
            'ca' => 'Catalan',
            'co' => 'Corsican',
            'cs' => 'Czech',
            'cy' => 'Welsh',
            'da' => 'Danish',
            'de' => 'German',
            'dz' => 'Bhutani',
            'el' => 'Greek',
            'eo' => 'Esperanto',
            'es' => 'Spanish',
            'et' => 'Estonian',
            'eu' => 'Basque',
            'fa' => 'Persian',
            'fi' => 'Finnish',
            'fj' => 'Fiji',
            'fo' => 'Faeroese',
            'fr' => 'French',
            'fy' => 'Frisian',
            'ga' => 'Irish',
            'gd' => 'Scots/Gaelic',
            'gl' => 'Galician',
            'gn' => 'Guarani',
            'gu' => 'Gujarati',
            'ha' => 'Hausa',
            'hi' => 'Hindi',
            'hr' => 'Croatian',
            'hu' => 'Hungarian',
            'hy' => 'Armenian',
            'ia' => 'Interlingua',
            'ie' => 'Interlingue',
            'ik' => 'Inupiak',
            'in' => 'Indonesian',
            'is' => 'Icelandic',
            'it' => 'Italian',
            'iw' => 'Hebrew',
            'ja' => 'Japanese',
            'ji' => 'Yiddish',
            'jw' => 'Javanese',
            'ka' => 'Georgian',
            'kk' => 'Kazakh',
            'kl' => 'Greenlandic',
            'km' => 'Cambodian',
            'kn' => 'Kannada',
            'ko' => 'Korean',
            'ks' => 'Kashmiri',
            'ku' => 'Kurdish',
            'ky' => 'Kirghiz',
            'la' => 'Latin',
            'ln' => 'Lingala',
            'lo' => 'Laothian',
            'lt' => 'Lithuanian',
            'lv' => 'Latvian/Lettish',
            'mg' => 'Malagasy',
            'mi' => 'Maori',
            'mk' => 'Macedonian',
            'ml' => 'Malayalam',
            'mn' => 'Mongolian',
            'mo' => 'Moldavian',
            'mr' => 'Marathi',
            'ms' => 'Malay',
            'mt' => 'Maltese',
            'my' => 'Burmese',
            'na' => 'Nauru',
            'ne' => 'Nepali',
            'nl' => 'Dutch',
            'no' => 'Norwegian',
            'oc' => 'Occitan',
            'om' => '(Afan)/Oromoor/Oriya',
            'pa' => 'Punjabi',
            'pl' => 'Polish',
            'ps' => 'Pashto/Pushto',
            'pt' => 'Portuguese',
            'qu' => 'Quechua',
            'rm' => 'Rhaeto-Romance',
            'rn' => 'Kirundi',
            'ro' => 'Romanian',
            'ru' => 'Russian',
            'rw' => 'Kinyarwanda',
            'sa' => 'Sanskrit',
            'sd' => 'Sindhi',
            'sg' => 'Sangro',
            'sh' => 'Serbo-Croatian',
            'si' => 'Singhalese',
            'sk' => 'Slovak',
            'sl' => 'Slovenian',
            'sm' => 'Samoan',
            'sn' => 'Shona',
            'so' => 'Somali',
            'sq' => 'Albanian',
            'sr' => 'Serbian',
            'ss' => 'Siswati',
            'st' => 'Sesotho',
            'su' => 'Sundanese',
            'sv' => 'Swedish',
            'sw' => 'Swahili',
            'ta' => 'Tamil',
            'te' => 'Tegulu',
            'tg' => 'Tajik',
            'th' => 'Thai',
            'ti' => 'Tigrinya',
            'tk' => 'Turkmen',
            'tl' => 'Tagalog',
            'tn' => 'Setswana',
            'to' => 'Tonga',
            'tr' => 'Turkish',
            'ts' => 'Tsonga',
            'tt' => 'Tatar',
            'tw' => 'Twi',
            'uk' => 'Ukrainian',
            'ur' => 'Urdu',
            'uz' => 'Uzbek',
            'vi' => 'Vietnamese',
            'vo' => 'Volapuk',
            'wo' => 'Wolof',
            'xh' => 'Xhosa',
            'yo' => 'Yoruba',
            'zh' => 'Chinese',
            'zu' => 'Zulu',
        ];

        $languages_fr = [
            'en' => 'Anglais',
            'aa' => 'Afar',
            'ab' => 'Abkhaze',
            'af' => 'Afrikaans',
            'am' => 'Amharique',
            'ar' => 'Arabe',
            'as' => 'Assamais',
            'ay' => 'Aymara',
            'az' => 'Azerbaïdjanais',
            'ba' => 'Bachkir',
            'be' => 'Biélorusse',
            'bg' => 'Bulgare',
            'bh' => 'Bihari',
            'bi' => 'Bislama',
            'bn' => 'Bengali / Bangla',
            'bo' => 'Tibétain',
            'br' => 'Breton',
            'ca' => 'Catalan',
            'co' => 'Corse',
            'cs' => 'Tchèque',
            'cy' => 'Gallois',
            'da' => 'Danois',
            'de' => 'Allemand',
            'dz' => 'Bhutani',
            'el' => 'Grec',
            'eo' => 'Espéranto',
            'es' => 'Espanol',
            'et' => 'Estonien',
            'eu' => 'Basque',
            'fa' => 'Persan',
            'fi' => 'Finlandais',
            'fj' => 'Fidji',
            'fo' => 'Féroé',
            'fr' => 'Français',
            'fy' => 'Frison',
            'ga' => 'Irlandais',
            'gd' => 'Écossais / gaélique',
            'gl' => 'Galicien',
            'gn' => 'Guarani',
            'gu' => 'Gujarati',
            'ha' => 'Hausa',
            'hi' => 'Hindi',
            'hr' => 'Croate',
            'hu' => 'Hongrois',
            'hy' => 'Arménien',
            'ia' => 'Interlingua',
            'ie' => 'Interlingue',
            'ik' => 'Inupiak',
            'in' => 'Indonésien',
            'is' => 'Islandais',
            'it' => 'Italien',
            'iw' => 'Hébreu',
            'ja' => 'Japonais',
            'ji' => 'Yiddish',
            'jw' => 'Javanais',
            'ka' => 'Géorgien',
            'kk' => 'Kazakh',
            'kl' => 'Groenlandais',
            'km' => 'Cambodgien',
            'kn' => 'Kannada',
            'ko' => 'Coréen',
            'ks' => 'Kashmiri',
            'ku' => 'Kurde',
            'ky' => 'Kirghiz',
            'la' => 'Latin',
            'ln' => 'Lingala',
            'lo' => 'Laothien',
            'lt' => 'Lituanien',
            'lv' => 'Letton',
            'mg' => 'Malgache',
            'mi' => 'Maori',
            'mk' => 'Macédonien',
            'ml' => 'Malayalam',
            'mn' => 'Mongol',
            'mo' => 'Moldave',
            'mr' => 'Marathi',
            'ms' => 'Malais',
            'mt' => 'Maltais',
            'my' => 'Birman',
            'na' => 'Nauru',
            'ne' => 'Népalais',
            'nl' => 'Néerlandais',
            'no' => 'Norvégien',
            'oc' => 'Occitan',
            'om' => '(Afan)/Oromoor/Oriya',
            'pa' => 'Punjabi',
            'pl' => 'Polonais',
            'ps' => 'Pashto/Pushto',
            'pt' => 'Portugais',
            'qu' => 'Quechua',
            'rm' => 'Rhéto-Romance',
            'rn' => 'Kirundi',
            'ro' => 'Roumain',
            'ru' => 'Russe',
            'rw' => 'Kinyarwanda',
            'sa' => 'Sanskrit',
            'sd' => 'Sindhi',
            'sg' => 'Sangro',
            'sh' => 'Serbo-croate',
            'si' => 'Cingalais',
            'sk' => 'Slovaque',
            'sl' => 'Slovène',
            'sm' => 'Samoan',
            'sn' => 'Shona',
            'so' => 'Somali',
            'sq' => 'Albanais',
            'sr' => 'Serbe',
            'ss' => 'Siswati',
            'st' => 'Sesotho',
            'su' => 'Sundanais',
            'sv' => 'Suédois',
            'sw' => 'Swahili',
            'ta' => 'Tamil',
            'te' => 'Télougou',
            'tg' => 'Tadjik',
            'th' => 'Thaïlandais',
            'ti' => 'Tigrinya',
            'tk' => 'Turkmène',
            'tl' => 'Tagalog',
            'tn' => 'Setswana',
            'to' => 'Tonga',
            'tr' => 'Turc',
            'ts' => 'Tsonga',
            'tt' => 'Tatar',
            'tw' => 'Twi',
            'uk' => 'Ukrainien',
            'ur' => 'Ourdou',
            'uz' => 'Ouzbek',
            'vi' => 'Vietnamien',
            'vo' => 'Volapuk',
            'wo' => 'Wolof',
            'xh' => 'Xhosa',
            'yo' => 'Yoruba',
            'zh' => 'Chinois',
            'zu' => 'Zoulou',
        ];

        foreach ($languages_en as $code => $languagename) {
            $language = new Language();
            $language->setCode($code);
            $language->setName($languagename);
            $language->setSlug($this->slugger->slug($language->getName())->lower());
            $manager->persist($language);
        }

        $manager->flush();
    }
}
